### ISSUE TITLE
proposal :Range query in row ids

### ISSUE THREAD

**Issue by zongwu233** [FeatureBaseDB/featurebase#1029]
### Description

I create a frame with unique numbers  as  column ids and some  type as row ids, it works well but sometimes I need query like  Count(Bitmap(frame="datas",  rowID >< [200,1234])) .
an workaround is use Union   : Count(Bitmap(frame="datas",rowID=200),Bitmap(frame="datas",rowID=201)... Bitmap(frame="datas",rowID=1234)) . 
Not simple at all.

### Success criteria (What criteria will consider this ticket closeable?)
support  > , < ,   >= ,  <= ,   >< operator  on rowID for range query .

**Comment by jaffee** [comment]
@zongwu233 I really like this idea - let me just restate it to make sure I understand.

Basically, you'd like a way to express queries which include lots of rows in the same frame in a more compact way. So something like:

```
Union(Bitmap(frame="datas", rows=[29-32]))
```
would be the same as doing:
```
Union(Bitmap(frame="datas",rowID=29), Bitmap(frame="datas",rowID=30), Bitmap(frame="datas", rowID=31), Bitmap(frame="datas",rowID=32))
```

**Comment by zongwu233** [comment]
@jaffee  YES ~

**Comment by jaffee** [comment]
@zongwu233 this has proved to be a fairly contentious change for reasons we discussed in the linked PR #1122 - have you been able to work around this, or is it still a significant problem for you? Could you give us some more context about the use-case which is behind this feature, and why it would be useful for you?

**Comment by zongwu233** [comment]
@jaffee I wanted to create a realtime user-profile-compute server a few months ago. You can choose some kinds of user tags ( gender, city, age and so on ) and some combined operator ( &&, ||,  <, >, == ) ,then server calculate the result ( the  count of result, and the users) immediately. 
After I researched several days, I focus on bitset op and refined my requirements. After read an aticle of **Pilosa** ,I realized Pilosa is The chiose.
In many case, the user tags are rangable, such as City Zip from 110000 to 820000, users are distributed throughout Zips , and one Zip mapped to one frame( columnid is userId,is common to all frame in a index,and rowid is tag value ) . 
Why not to use BSI field ? its supported operator is poor ,and cannot combine operator with annother frame . Another reason is I can manage the meta data of frames , some calcluate can tranform to meta data to void massive bitmap calculate. 
For example : `30 < today - last_login_date  < 7` , the best way is caclulate this expression on meta data and then caclulate on bitmap. that's why I need a Union operator on several frames. Some case I need use `%` `/` operator to calculate expression.
