### ISSUE TITLE
import endpoints not covered in api docs

### ISSUE THREAD

**Issue by jaffee** [FeatureBaseDB/featurebase#1127]
We should take a look at the API Reference section of our docs and make sure we  cover anything which implemented in the clients. I know some things we don't want to officially expose and support, but /import and import-value are pretty widely used at this point..

**Comment by travisturner** [comment]
@codysoyland is going to review the import endpoints again to determine if it makes sense to consolidate them into one.

**Comment by yuce** [comment]
Is this still good to work on ?

**Comment by codysoyland** [comment]
We've had a little discussion about combining the two import urls into a singular handler and locking down the API. I still feel like that might be the best option, but I haven't looked at it in a while. I would like to make that decision before documenting them.

**Comment by travisturner** [comment]
We don't have an `import-value` endpoint anymore, but we have since added `import-roaring`. I think this issue is still valid and API updates are needed.
