### ISSUE TITLE
ability to retrieve min/max column ids for an index

### ISSUE THREAD

**Issue by jaffee** [FeatureBaseDB/featurebase#1385]
### Description

Related to #316 and #807. There are a number of situations where knowing the maximum column ID would be helpful, and knowing the minimum may be necessary as well for some usages. In addition to what's mentioned in the tickets, knowing where to start allocation column ids when restarting an ingest process is another example.

**Comment by travisturner** [comment]
With #1628 (`trackExistence`), this should be fairly straight forward now.

It would be useful to propose an interface for this. I assume it would just be an http endpoint, calling a new, exported `api` method. Perhaps something like:
```
router.HandleFunc("/internal/index/{index}/min-column", ...)
router.HandleFunc("/internal/index/{index}/max-column", ...)
```
Or maybe not `internal`?
