### ISSUE TITLE
/import endpoint should forward to the correct node (which owns the shard)

### ISSUE THREAD

**Issue by jaffee** [FeatureBaseDB/featurebase#1589]
It should probably handle the replication too - right now the clients issue separate requests for replicas.

This will make it easier to support things like imports behind a load balancer as in #1129

Todd's import-roaring work does this, and so may be a good reference. We've also talked about functionality like this for imports with string keys in #1557

**Comment by travisturner** [comment]
We are building a prototype which allows any node to receive an import request from the client, determine the destination of the import, and, if the destination is another node in the cluster, forward the request to that node.

The client will have the ability to provide destination information (for example, to which shard the import applies), and if the client is cluster-aware, can still send import requests to a specific node. But the client will also have the option of sending the import to any node in the cluster and that import will be forwarded to the correct node (this may even be a requirement for cases where Pilosa is behind a proxy and it's not possible to address a specific node).

The routing information provided by the client will include:
- index
- field
- shard
- hasKeys (this argument name still TBD)

Providing this information along with the import payload allows the receiving node to determine final destination and forward the payload without having to unmarshal and inspect its contents. If, however, the ultimate recipient of the import payload determines that the import data is invalid (i.e. it does not correspond to its destination information), it will return an error.
