### ISSUE TITLE
Pilosa on Google Cloud

### ISSUE THREAD

**Issue by yuce** [FeatureBaseDB/featurebase#1590]
### Description

I tried to create a test setup on Google Cloud, but wasn't successful. The external IP interface is not on the VMs, so something like `pilosa -b p01.domain.com` wasn't possible (I think there is a way to do that with setting up forwarding, but it wasn't obvious how to do that). I could run `pilosa -b 0.0.0.0` but then I wouldn't be able to use it in `cluster.hosts`. If the bind address is not in `cluster.hosts` the server doesn't like that and exits with `missing bind address in cluster hosts`.

I'll be checking the code about it, but do we really require the bind address to be in `cluster.hosts`, or is it only for warning the user that they need to set the bind address (and the server should be accessible with the bind address).
If that's not a hard requirement, it would be great to remove the requirement that the bind address to be exist in `cluster.hosts`. Without that constraint, we could just `-b 0.0.0.0` and put `p01.domain.com`  in `--cluster.hosts`. `p01.domain.com` resolves when accessed externally.

### Success criteria (What criteria will consider this ticket closeable?)

Pilosa works on Google Cloud. Probably by allowing Pilosa bind to a different IP than the external IP.

**Comment by jaffee** [comment]
related to #1718, #1129, #1113
