### ISSUE TITLE
GroupBy on time field without standard view error

### ISSUE THREAD

**Issue by dmibor** [FeatureBaseDB/featurebase#1844]
For bugs, please provide the following:

### What's going wrong?
trying to do GroupBy query on time field without standard view - get the following error
```
curl localhost:10101/index/test_index/query -X POST -d 'GroupBy(Rows(f1),Rows(f2),Rows(f3))'
{"error":"parsing: parsing: \nparse error near IDENT (line 1 symbol 14 - line 1 symbol 21):\n\"f1\"\n"}
```
### What was expected?
Working GroupBy for time fields without standard view
### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

**Comment by yuce** [comment]
`Rows` call is currently not supported for "no standard view":
```
$  curl localhost:10101/index/i1/field/f3 -d '{"options":{"type":"time", "timeQuantum":"YMD","noStandardView":true}}'
$  curl localhost:10101/index/i1/query -d 'Rows(f3)'
{"error":"executing: Rows() query on time field with no standard view is not currently supported"}
```

The error you receive is not related to *no standard view* though, removing the quotes around the field name should make the query work:
```
$ curl localhost:10101/index/i1/query -d 'Rows("f2")'
{"error":"parsing: parsing: \nparse error near open (line 1 symbol 5 - line 1 symbol 6):\n\"(\"\n"}

$ curl localhost:10101/index/i1/query -d 'Rows(f2)'
{"results":[{"rows":[]}]}
```

**Comment by yuce** [comment]
`GroupBy` call should have returned an error for the `Rows` call with no standard view. Created this issue to to track that: https://github.com/pilosa/pilosa/issues/1845

**Comment by dmibor** [comment]
Ok, would be good then to have GroupBy working for time fields with no standard view - so that it's possible for us to start using GroupBy as it's very useful and long awaited feature...

That should work out of the box as soon as Rows() that accept time ranges is done, do i get it right?

**Comment by yuce** [comment]
That's right.

**Comment by travisturner** [comment]
#1851 added from/to range support to the `Rows()` operation. I believe that in order for this to be useful in `GroupBy` we need to pass the from/to arguments down to the part of the `GroupBy` operation that is retrieving the `Row` data, so effectively the row-intersections which are happening are taking the provided time range (associated to each field) into account.

I'll leave this ticket open in order to track that work.

**Comment by dmibor** [comment]
@travisturner think you are right, just having time range in Rows() didn't help, still get empty response in my GroupBy:
```
curl coordinator:10101/index/main/query -X POST -d 'GroupBy(Rows(field1))'
{"results":[[]]}
```

**Comment by jaffee** [comment]
blocked by other group by work—best to only have one thing in-flight at a time in this part of the code.
