### ISSUE TITLE
Intermittent failure in server/server_test.go

### ISSUE THREAD

**Issue by jaffee** [FeatureBaseDB/featurebase#1878]
This test is setting 100 bits in 100 different shards via 100 `Set` calls concatenated in a single request to a 3-node in-memory cluster.

This happens occasionally - I've seen 98 and 99. It seems to be the last bits/shards which are missing:

```
--- FAIL: TestClusterQueriesAfterRestart (1.04s)
    server_test.go:776: Count should be 100, but got 98 of type uint64
FAIL
FAIL	github.com/pilosa/pilosa/server	77.115s
```

I'm wondering if this is somehow related to the recent changes to broadcasting createshard messages (part of the fix to the flock bug), though I don't immediately see how it could be.

**Comment by travisturner** [comment]
I just experienced this running tests locally.
