### ISSUE TITLE
Rust client support

### ISSUE THREAD

**Issue by cih-y2k** [FeatureBaseDB/featurebase#1879]
Rust's ecosystem is growing very fast and it's async model is suitable for large multi-data center applications. So, Pilosa should have a Rust client.

**Comment by yuce** [comment]
Hi @cih-y2k. Rust is a great language, but we don't have any plans for an official Rust client library in the near future. We welcome client libraries from the community though. Let me know if you if have questions about implementing a client library, and I'll help. We have a (slightly outdated) article about [Writing a Pilosa Client Library](https://www.pilosa.com/blog/writing-a-client-library/) in case you are interested.

**Comment by cih-y2k** [comment]
Thank you @yuce I'll give it a try.

**Comment by jaffee** [comment]
Rust is so cool! I wish we had the bandwidth to do this - let us know if you have any questions @cih-y2k!
