### ISSUE TITLE
PQL can silently ignore typos

### ISSUE THREAD

**Issue by seebs** [FeatureBaseDB/featurebase#1957]
### What's going wrong?

`Rows(colum=3)` does not produce an error.

### What was expected?

Probably a diagnostic. When something's a field name, I believe we report if there's no such field, but when something's grammatically field-name-like in the PEG grammar, but not actually used as a field, it may be ignored silently.

### Steps to reproduce the behavior

See above.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

N/A.

**Comment by seebs** [comment]
I'm still thinking about this but probably going to try to address it shortly in passing as part of looking at adding some functionality.

**Comment by jaffee** [comment]
this will probably get solved as part of plugin work... but let's revisit and make sure.
