### ISSUE TITLE
gracefully handle bogus .available.shards files

### ISSUE THREAD

**Issue by seebs** [FeatureBaseDB/featurebase#2055]
### What's going wrong?

If someone's filesystem creates 0-byte `.available.shards` files, pilosa can fail to start up because it can't read them.

### What was expected?

Well, probably a working filesystem, but I think that's out of scope. I think we should handle that case gracefully.

So far as I can tell, the `.available.shards` files are functionally a cache -- they can be recreated at runtime by querying other nodes. If we can't read them, we should ignore them rather than failing.

### Steps to reproduce the behavior

Zero out the files while pilosa is down, start it up.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Affected systems were Centos using XFS, but it's irrelevant.

**Comment by travisturner** [comment]
@seebs has any work been done on this? should we keep it as "In Progress"?

**Comment by seebs** [comment]
It's actually the first commit in my fsck branch (which means it's stacked under a ton of other changes), so a fix exists, it's just not merged.
