### ISSUE TITLE
Querying an int field with single '=' returns no results, but should probably error

### ISSUE THREAD

**Issue by jaffee** [FeatureBaseDB/featurebase#2085]
If we have a field called `size` which is an int, and we query it like `Count(Row(size=10))` we get `0` back.

If we query it like `Count(Row(size==10))` (the correct way), we get the expected result based on the data in the field.

`Row(size=10)` should either (a) return an error, or (b) return the actual row 10 on the size field which would represent which records have their 9th binary digit as 1 for size. (because row 0 and 1 are used for existence and sign).  I would actually lean toward the latter.

**Comment by travisturner** [comment]
might there also be an option (c) treat `Row(size=10)` the same as `Row(size==10)`?
still, i'm leaning toward (a) with some kind of "did you mean == ?" error message.
while (b) is intriguing, i think it would lead to confusion and unexpected, "incorrect" results.
