### ISSUE TITLE
PQL Clear should support int fields as well as bits

### ISSUE THREAD

**Issue by jaffee** [FeatureBaseDB/featurebase#2086]
It should be possible to clear integer values via PQL, e.g.

`Clear(<col>, intfield=x)`

If we follow our import logic, this would actually set the intfield at <col> equal to `x` and then clear the existence bit. Alternatively, it might be more intuitive if it only cleared the value if it were equal to x, if it just ignored x, if it didn't take an x parameter at all and was just `Clear(<col>, intfield)`. I think I'd be in favor of mirroring our import logic, but also supporting that last syntax which would behave equivalently to `Clear(<col>, intfield=0)`

**Comment by CLoZengineer** [comment]
closing this with move towards to SQL3
