### ISSUE TITLE
When will it restore to develop? 

### ISSUE THREAD

**Issue by zhyhang** [FeatureBaseDB/featurebase#2095]
There is not any commit  last days. When will restore?

**Comment by jaffee** [comment]
Hi @zhyhang! sorry for the delay, rest assured we are very much still here. For the last few weeks we've been heavily focused on our enterprise product as we have a launch coming up at the end of February. Going forward you should expect to see activity pick back up a bit as we can free up resources to do core Pilosa work.

**Comment by zhyhang** [comment]
@jaffee Thanks!
