### ISSUE TITLE
Why not use BSTM to calculate TopK

### ISSUE THREAD

**Issue by xiehuc** [FeatureBaseDB/featurebase#2101]
i think pilosa use cache and min heap to calculate TopK

but since pilosa use bsi heavly, and there are a paper introduced BSTM 
which means (Bit Slice Term Match) algorithm to calculate TopK

it would be very suitable for pilosa

https://www.researchgate.net/publication/221215144_Bit-Sliced_Index_Arithmetic

![截屏2020-04-01 下午2 47 38](https://user-images.githubusercontent.com/571878/78107272-beb06800-7427-11ea-8d00-661bdda91505.png)

**Comment by kuba--** [comment]
Thanks @xiehuc for sharing.
We're working to improve performance of aggregation functions. Moreover `TopN` implementation on integers is missed, right now. So, I think it's totally worth to consider the white-paper, which you mentioned.

**Comment by Smallhi** [comment]
@xiehuc  see https://github.com/lemire/BitSliceIndex/tree/master/src/main/java/org/roaringbitmap/circuits/topk, the author of roaringBitmap write two type of algorithm for topK, one is  RinfretONeil, one is simple by Tree

**Comment by jaffee** [comment]
interesting... I had totally forgotten about this. @niaow is this similar to what you did?

**Comment by xiehuc** [comment]
that's cool, i'd see it later.
