### ISSUE TITLE
Server not start up, Error: checksum mismatch

### ISSUE THREAD

**Issue by young118** [FeatureBaseDB/featurebase#2121]
### What's going wrong?
I have a pilosa server running in docker. There is another process keep inserting data into pilosa, and pilosa runs normally for like 2 weeks, but someday suddenly pilosa can not start up,  docker logs shows the following error:
Error: running server: opening server: opening Holder: open index: name=packet_packet, err=opening fields: open field: name=_exists, err=opening views: opening view: view=standard, err=opening fragments: open fragment: shard=5, err=opening storage: unmarshal storage: file=/data/packet_packet/_exists/views/standard/fragments/5, err=unmarshaling as pilosa roaring: checksum mismatch: type 0, exp=c8e581ff, got=00000000, 
could anyone tell me what does this mean and how to resolve it, thanks.

### What was expected?
I wanna know why this happened and how to fix it.
### Steps to reproduce the behavior
Sorry I really don't know how to reproduce it, I keep inserting almost the same data into pilosa, and there isn't any inappropriate operation on the server these days.
### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
OS: ubuntu18.04
CPU:4 core
RAM: 16GB
solo
default configuration

**Comment by seebs** [comment]
Is it possible that you ran out of disk space (possibly temporarily) on that machine?

How large is the file it's reporting this on (the fragments/5 file) in bytes?

**Comment by young118** [comment]
@seebs The docker container is down, I can't check the size of fragments/5 now, but I'm pretty sure that I did not ran out of disk space, the total disk usage is just 40G

**Comment by young118** [comment]
I know what caused this now, it was the ungracefully shutting down. I can not control how my client use my product, so my question is, how can I recover data from this? Thanks
