### ISSUE TITLE
Column attributes can't be used

### ISSUE THREAD

**Issue by alanbernstein** [FeatureBaseDB/featurebase#2131]
For bugs, please provide the following:

### What's going wrong?
Column attributes can't be used

### What was expected?
Column attributes can be written and read

### Steps to reproduce the behavior

`curl http://127.0.0.1:10101/index/i/query -d"SetColumnAttrs(1, foo='bar')"`

`{"results":[null]}`

This is the expected response when writing, but the write success/failure isn't obvious.

`curl http://127.0.0.1:10101/index/i/query -d"Options(TopN(f), columnAttrs=true)"`

or

`curl http://127.0.0.1:10101/index/i/query?columnAttrs=true -d"TopN(f)"`

`{"results":[[{"id":0,"key":"","count":11}]]}`

This result should include "columnAttrs" at the top level.

**Comment by jaffee** [comment]
column attributes are no longer a thing
