### ISSUE TITLE
Special characters in imported key cause error in query

### ISSUE THREAD

**Issue by threedliteguy** [FeatureBaseDB/featurebase#2133]
For bugs, please provide the following:

### What's going wrong?
After importing keys, curl query using Row(field="") returned the following error:
Row error with arg for row: could not convert of type string to unit64 in Call.UintArg
### What was expected?
Able to use any string for key
### Steps to reproduce the behavior
Using command line import to a keyed field, set key value to string including a character ascii 160 (non-breaking space)
### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
linux

Workaround is to strip the special characters from keys before importing.

**Comment by kuba--** [comment]
@threedliteguy - could you copy-paste your schema here (index and field options).
