### ISSUE TITLE
build-lattice Makefile target failing

### ISSUE THREAD

**Issue by Herkemer** [FeatureBaseDB/featurebase#2161]
Looks like there is a custom docker container being used for the build-lattice step.  Can that be pointed to a publicly available container or the Dockerfile updated to build with the correct dependencies?

**Comment by fhaynes** [comment]
Acknowledged, thanks! Shouldn't take me too long to resolve it.

**Comment by Herkemer** [comment]
Just to followup, the steps in the lattic/Dockerfile are also in the top level Dockerfile, just want to make sure you saw both places.
