### ISSUE TITLE
go.mod `module` needs to be updated to reflect the featurebasedb github org

### ISSUE THREAD

**Issue by clowenhg** [FeatureBaseDB/featurebase#2165]
Currently the go.mod module is
`module github.com/molecula/featurebase/v3`

This needs to be updated to reflect the new FeatureBaseDB and current version.

**Comment by reesporte** [comment]
https://github.com/FeatureBaseDB/featurebase/blob/51249cda781e42136234f9329d7af0dcc6b6f1b8/go.mod#L1 looks like it's already up to date! unless there's a new major version to be updated to?

**Comment by CLoZengineer** [comment]
You are correct @reesporte 
I had the wrong version of the code I was looking at, thanks.
