### ISSUE TITLE
Ensure Lattice builds with latest NodeJS v18

### ISSUE THREAD

**Issue by CLoZengineer** [FeatureBaseDB/featurebase#2191]
Current Lattice build in our workflows have only been tested against Node v14 and v16 and are unsuccessful when built with v16.

AC:
1. Lattice builds with NodeJS v18 in all workflows

**Comment by kordless** [comment]
@ch7ck determine the status of this and close or update this ticket to reflect the work needing to be done.

**Comment by jaffee** [comment]
Closing until someone tells me this is a priority.
