### ISSUE TITLE
Windows 

### ISSUE THREAD

**Issue by gedw99** [FeatureBaseDB/featurebase#2298]
Would like to know what’s the blocker on a native windows install. 

Might be file system watcher or some system dependency .

Can’t be cgo as the code base is pure go.

I am because I have use cases where I need to do computer at the edge. 

Congrats on new name and company btw . Pilosa was a dark horse that was not appreciated as it was too early perhaps

**Comment by jaffee** [comment]
Thanks @gedw99 main blocker for windows is our use of mmap I believe. There maybe a few other system level things like that which we do (checking/setting open file limits for example). If you want to try to get a windows build going, I'd be happy to give pointers, but it's not something the company has a compelling reason to spend resources on right now.

> Congrats on new name and company btw . Pilosa was a dark horse that was not appreciated as it was too early perhaps

Thank you for the kind words. Pilosa was very powerful, but narrow and difficult to use properly. With a full SQL engine, we hope FeatureBase can expose Pilosa's core innovations in a much more user-friendly and easy-to-appreciate kind of way :)

**Comment by gedw99** [comment]
Let me try it myself first 
M the use case is ml people have windows and don’t like to run docker..
