### ISSUE TITLE
Nats ingestion 

### ISSUE THREAD

**Issue by gedw99** [FeatureBaseDB/featurebase#2328]
It’s a golang alternative to Kafka.

would be great as nats is more performant that Kafka

**Comment by jaffee** [comment]
Unlikely to happen in the short term, but will certainly keep this open to gauge interest.

**Comment by gedw99** [comment]
Fair enough .

**Comment by gedw99** [comment]
@jaffee 

https://m.youtube.com/watch?v=C4BnJ5QLeTY

It’s comparing Kafka and nats from a perf and feature pov.

i used both and the one before them called Tibco Rendezvous.

the api aspects are almost the same. Nats has the advantage that it runs anywhere and it’s commonly put onto IOT devices and globally distributed clusters
