### ISSUE TITLE
Support extended attributes for frames and databases

### ISSUE THREAD

**Issue by alanbernstein** [FeatureBaseDB/featurebase#316]
**Pilosa should maintain some additional information about databases and frames**, and allow users to set, modify, and view it, as appropriate. For the sake of consistency I refer to this information as "attributes", although Pilosa currently uses the terms "options" and "schema" for similar features.

Like BitmapAttrs and ProfileAttrs, FrameAttrs and IndexAttrs should support storing arbitrary key-value pairs. Additionally, **certain reserved keys should provide specific functionality**. Conceptually, rowLabel and columnLabel are examples of reserved keys. **Independently of (the rest of) this proposal, from a user's perspective, it is preferable to consolidate the terminology and interfaces for interacting with metadata**. The proposed Attrs system might incorporate rowLabel and columnLabel, or the current "options" system might incorporate new options.

## Existing similar functionality that could be consolidated

- SetProfileAttrs and SetBitmapAttrs PQL commands
  The current interface for these is sufficient in itself. Adding new functionality for FrameAttrs and IndexAttrs, via a new interface, would mean we have two different interfaces for working with different types of attributes.
- /schema endpoint
  Certain index and frame attributes are arguably part of the schema, so a user might expect to see this information available at the schema endpoint.
- "options" for databases and frames, as set at the /index and /frame endpoints
  From a user perspective, this interface already has significant overlap with new proposed attributes.

## Motivation 
A major motivation for this proposal is the desire for a system to support a generic web app that can automatically interface with any Pilosa database, as long as certain FrameAttr keys are defined. This app would bear some resemblance to the transportation demo, including summary and visualization components. These same features could also be used by the web console, or homepage demo. These components would be supported by at least three new FrameAttrs: rowMapping, maxRowID, description (in descending order of importance).

### rowMapping
In the case that row IDs represent external entities in some nontrivial way, a mapping must be maintained. If the mapping is just a big hashmap between rowIDs and strings, or rowIDs and external IDs, then this can't be captured compactly*. However, a straightforward mapping, like that used for indexing numeric data, can be represented compactly, and stored as an attribute. A machine-readable representation of the mapping can be used to reconstruct the function, or its inverse. The inverse function can then be used by a generic client to reconstruct the original data, or an approximation to it. 

I note that this is a speculative use case, but in the event that it becomes common, the ability to maintain the mapping used for a frame as metadata will be helpful. If the hashmap use case becomes predominant, then perhaps we should consider ~a feature to support that instead~ incorporating Nexter functionality here.

### maxRowID
Provides an easy way to check the largest row ID present in a frame. This is not currently available, but should at least be included in the reserved key list.

### description
A canonical place to store the main description of the frame, which might be used directly in an app.

### Database
- columnLabel (existing)
- description/comment (new)
- columnMapping (new)
- maxColumnID (new, read-only)
- name (new, setting changes the name of the database)

### Frame
- rowLabel (existing)
- timeQuantum (existing)
- inverted (existing)
- cacheType (existing)
- cacheSize (existing)
- description/comment (new, canonical description)
- rowMapping (new)
- maxRowID (new, read-only)
- rowIDLimit (new, simple validation for frames where going over the limit is nonsensical)
- name (new, setting changes the name of the frame)
- dataSource (new)

The full specification of rowMapping (and columnMapping) is a related but separate issue. It is also closely related to previous PDK work; there would be a close correspondence between PDK "Mapper" types, and the mappings supported as attributes. One example: 

```
type LinearFloatMapper struct {
	Min           float64
	Max           float64
	Res           float64
}
```
This might be represented in an attribute as a string like `LinearFloatMapper(0, 1000, 100)`, or maybe as a JSON object that reflects the structure of the PDK type.

## New Behavior
- set/update index attrs
- get index attrs
- set/update frame attrs
- get frame attrs

## Interface
I propose adding/modifying endpoints/PQL commands to support this. My interest is in supporting the functionality, I don't have a strong opinion on exactly what the interface should look like, but here are some possible approaches:

### HTTP
The endpoint could use the term "attrs", "schema", "options", "metadata". "Options" is overloaded with the HTTP method, and "schema" is somewhat narrow, if we want to allow arbitrary key-value storage. "attrs" is consistent with existing terminology, so this is my suggestion.

The actual endpoint might be `/schema/index/<indexname>/frame/<frame-name>` or something else.

The response from the /schema endpoint provides another option for a starting point for the responses to these queries. Expanded responses might look like the following:

`/schema` (all available attributes on the node):
```
{
    "indexes": [
        {
            "name": "taxi",
            "frames": [
                {
                    "name": "pickup_time",
                    "attrs": [
                        "description": "30-minute time-of-day buckets",
                        "maxBitmapID": 47,
                        "rowMapping": {
                            "mapper": "linearFloat",
                            "a": 2,
                            "b": 0,
                            "res": 48,
                        },
                        "units": "hours",
                        "rowIDLimit": 47
                    ],
                },
            ],
            "indexattrs": [
                "description": "taxi data stuff",
                "columnMapping": TODO
            ]
        },
    ],
}
```

`/schema/index/<indexname>/frame/<frame-name>` (attributes for specified frame):
```
{
    "name": "pickup_time",
    "attrs": [
        "description": "30-minute time-of-day buckets",
        "maxBitmapID": 47,
        "rowMapping": {
            "mapper": "linearFloat",
            "a": 2,
            "b": 0,
            "res": 48,
        },
        "units": "hours",
        "rowIDLimit": 47
    ],
}
```

### PQL
A second option; my preference is for the HTTP approach

- `SetIndexAttrs()`
   `SetIndexAttrs(index="taxi", description="taxi data stuff")`
   Response: `{"results":[null]}` for consistency
- `GetIndexAttrs()`
   `GetIndexAttrs(index="taxi")`
   Response: `{"description": "taxi data stuff", "maxColumnID": 123456789}`
   `GetIndexAttrs(index="taxi", "description")`
   Response: `{"description": "taxi data stuff"}`
- `SetFrameAttrs()`
   `SetFrameAttrs(index="taxi", frame="pickup_time", description="30-minute time-of-day buckets", maxBitmapID=47)`
   Response: `{"results":[null]}` for consistency
- `GetFrameAttrs()`
   `GetFrameAttrs(index="taxi", frame="pickup_time")`
   Response: `{"description": "30-minute time-of-day buckets", "maxBitmapID": 47}`
   `GetFrameAttrs(index="taxi", frame="pickup_time", "description")`
   Response: `{"description": "30-minute time-of-day buckets"}`

**Comment by jaffee** [comment]
We need to look closely at this and the input definition work #607  and see where overlap is.
