### ISSUE TITLE
Separate Tanimoto from TopN

### ISSUE THREAD

**Issue by linhvo** [FeatureBaseDB/featurebase#542]
For feature requests, please provide the following:

### Description
Remove Tanimoto from TopN then add a plugin for Tanimoto

### Success criteria (What criteria will consider this ticket closeable?)

To calculate tanimoto of bitmap with all others bitmaps (can be the same or different frame), using: `Tanimoto(Bitmap(rowID=1, frame=a), frame=b, threshold=90)`

Results return are all rowIDs that have tanimoto >= given threshold and their bits Count. Eg: 
`{"results":[[{"id":6228,"count":37},{"id":6223,"count":37}]]}`

**Comment by jaffee** [comment]
iceboxing until plugin stuff is merged

**Comment by yuce** [comment]
@jaffee I think we can close this one, Linh created a Tanimoto plugin at: https://github.com/linhvo/tanimoto

**Comment by jaffee** [comment]
we don't have plugin support in master, so this is stalled until that is finalized.
