### ISSUE TITLE
WIP: PQL Data Types

### ISSUE THREAD

**Issue by yuce** [FeatureBaseDB/featurebase#604]
# PQL Data Types

## Arguments

```
Union(Bitmap(frame="geo",     rowID=5), Bits(1, 100, 100))
----- ------ -----------      -------
|     |      |                |
|     |      call-2 kw arg 1  call-2 kw arg 2
|     call-2 name
|     --------------------------------  -----------------
|     |                                 |
|     call-1 pos arg 1                  call-1 pos arg 2
call-1 name
```

Arguments of a PQL call are validated before the corresponding code is executed. The return values are validated after the call ends.

### Positional Arguments

A PQL call may take zero or more positional arguments. All positional arguments should be of the same type.

### Keyword Arguments

A PQL call may take zero or more keyword arguments. All keyword arguments are optional during validation. Non-declared keyword arguments cannot be passed to the call.

## Return Values

A PQL call may optionally return a single value. If a value is being returned, its type should be declared.

## Proposed Data Types

* any: Any of the types below. Corresponds to Go `interface{}` in code but validated against accepted types. Identifier: `any`.
* bool: `true` or `false`. Corresponds to Go `bool` type. Identifier: `bool`.
* int: Signed 64bit integers. Corresponds to Go `int64` type. E.g., `512`. Identifier: `int`.
* string: UTF-8 encoded string. Corresponds to Go `string` type. E.g., `"Austin"`. Identifier: `string`.
* float: 64bit float type. Corresponds to Go `float64` type. E.g., `3.14`. Identifier: `float`.
* list of any: All items in the list must be of the same type, but the type maybe any of the supported types. Corresponds to Go `[]type`. E.g., `[1, 10, 20]`. Identifier: "TYPE list", e.g., `int list`.
* map of (string, any): The key of the map must be a string, but the value maybe any of the supported types. Corresponds to Go `map[string]interface{}`. E.g., `{foo: "bar", age: 55}`. Identifier: `map`.
* tagged bitmap: Corresponds to a map with the following structure: `{label: "LABEL", frame: "FRAME_NAME", bits: [list of ints], attrs: {map of (string, any)}}`. `label` contains the ID label, e.g, `columnID`, `rowID`. `label` maybe set to the empty string (`""`) to make the `bits` field represent a generic bitmap. Identifier: `bitmap`.

## Declaring PQL Calls

All PQL calls can be defined using the following properties in a validation perspective:
* Name of the call
* Type of the positional arguments
* Types of keyword arguments
* Type of return value

Which corresponds to the following Go struct:

```go
type PQLCallInfo struct {
    Name string
    PositionalArgumentType string
    KeywordArgumentTypes map[string]string
    ReturnType string
}
```

The following is how would `Union` call be defined:

```go
unionCall := &PQLCallInfo{
    Name: "Union",
    PositionalArgumentType: "bitmap",
    ReturnType: "bitmap",
}
```

Since row ID label and column ID label may be different for each index, special `$rowID` and `$columnID` keywords are used to denote those fields. Here's how we would define the `Bitmap` call:

```go
bitmapCall := &PQLCallInfo{
    Name: "Bitmap",
    KeywordArgumentTypes: map[string]string{
        "frame": "string",
        "$rowID": "int",
        "$columnID": "int",
    }
    ReturnType: "bitmap",
}
```

During validation, `$rowID` is replaced by the actual row ID label, and `$columnID` is replaced by the actual column ID label.

## Registering PQL Calls

Once a PQL call is defined, we can register it using `pilosa.RegisterPlugin`:

```go
pilosa.RegisterPlugin(unionCall, NewUnionPlugin)
```

#### Keyword Arguments

- frame: string
- rowID: int
- columnID: int

### Returns

- bool

#### Keyword Arguments

- frame: string
- rowID: int
- columnID: int

#### Returns

- bool

#### Keyword Arguments

- frame: string
- id: int

#### Returns

- tagged bitmap (row OR column)

#### Positional Arguments

- row bitmap

#### Returns

- int

#### Positional Arguments

- tagged bitmap (row OR column)

#### Keyword Arguments

- n: int
- (opt) frame: string
- (opt) field: string
- (opt) filters: list of ints
- (opt) threshold: int
- (opt) tanimotoThreshold: int

#### Returns

- list of map(id, count)

#### Positional Arguments

- row bitmaps...

#### Returns

- row bitmap

#### Keyword Arguments

- frame: string
- start: string (of timequantum)
- end: string (of timequantum)

#### Returns

- row bitmap

#### Keyword Arguments

- frame: string
- rowID: int
- *: string OR int OR bool OR float

#### Returns

- null

#### Keyword Arguments

- columnID: int
- *: string OR int OR bool OR float

#### Returns

- null

### SetBit

* Keyword argument types: `frame=string`, `$rowID=int`, `$columnID=int`
* Return type: `bool`

### ClearBit

* Keyword argument types: `frame=string`, `$rowID=int`, `$columnID=int`
* Return type: `bool`

### Bitmap

* Keyword argument types: `frame=string`, `$rowID=int`, `$columnID=int`
* Return type: `bitmap`

### Count

* Positional argument type: `bitmap`
* Return type: `int`

### TopN

* Positional argument type: `bitmap`
* Keyword argument types: `n=int`, `frame=string`, `field=string`, `filters=int list`, `threshold=int`, `tanimotoThreshold=int`
* Return type: `map`

#### Positional Arguments

* Positional argument type: `bitmap`
* Return type: `bitmap`

### Range

* Keyword argument types: `frame=string`, `start=string`, `end=string`
* Return type: `bitmap`

### SetRowAttrs

* Keyword argument types: `frame=string`, `$rowID=int`, `attrs=map`

#### Keyword Arguments

* Keyword argument types: `frame=string`, `$columnID=int`, `attrs=map`

**Comment by yuce** [comment]
Updated with following changes:
* Made it clear that positional arguments should be of the same type.
* Added type identifiers.
* Added *Declaring PQL Calls* and *Registering PQL Calls* sections.

**Comment by yuce** [comment]
Updated with the following change:
* Added *Proposed Definitions for Existing PQL Calls* section

**Comment by jaffee** [comment]
Even though this proposal is over a year old, and we've rewritten and significantly changed PQL in the interim, there is still some good fodder for consideration. In particular, having some well-defined mechanism for registering new functionality with PQL that will be accepted by the parser is a solid idea.

Let's keep this in mind as we evolve PQL and plugins.
