### ISSUE TITLE
Return RowAttrs in TopN queries

### ISSUE THREAD

**Issue by travisturner** [FeatureBaseDB/featurebase#633]
### Description
For TopN queries, we should support the ability to return the `RowAttrs` associated to the rows (the `"id"` portion of the TopN result list).

We could support something similar to the `columnAttrs` query argument.

We need to decide how this would affect the results format; TopN result set is currently just a list and wouldn't easily support a new key like `attrs`. We may need to break the TopN result format in order to support this.

### Success criteria (What criteria will consider this ticket closeable?)
A TopN query result can optionally contain the `RowAttrs` (or I suppose `ColumnAttrs` in the case of an inverse frame) in the result set.

**Comment by jaffee** [comment]
The TopN result set is actually a list of objects: `{"results":[[{"id":10,"count":11},{"id":0,"count":11},{"id":2,"count":11},{"id":4,"count":11},{"id":3,"count":11}...]]}`,  so we could probably just add the attrs to those objects.

**Comment by jaffee** [comment]
This should probably be implemented as an optional argument to TopN `with-attrs=true` (think more about the naming though)

**Comment by yuce** [comment]
Can we consider never returning the attributes for TopN and Bitmap queries and have another PQL call (like `GetRowAttrs`, `GetColumnAttrs`) which would return attributes for the given row/column IDs?

**Comment by yuce** [comment]
Instead of a PQL call, an http endpoint for returning attributes may be easier to implement.

**Comment by jaffee** [comment]
Anybody remember where this requirement came from?

**Comment by travisturner** [comment]
I don't remember. I believe it was an Umbel-like use case where rows might represent tags, and returning a row attribute containing the tag name would prevent having to look up tag name in an external database. But in that example, row keys might be enough to satisfy that. I think it would be safe to icebox this.
