### ISSUE TITLE
Proposal: Importing/Exporting Row and Column Attributes

### ISSUE THREAD

**Issue by yuce** [FeatureBaseDB/featurebase#753]
# Importing/Exporting Row and Column Attributes

## Introduction

Currently Pilosa supports importing and exporting bits of slices. There is no attribute import/export support.

In this document, we propose a way to implement import/export support using existing mechanisms in Pilosa.

## Exporting Attributes

A block is a group of bits and their attributes. Pilosa uses blocks as a synchronization primitive. The block ID corresponding to a row or column is determined by dividing row or column ID by block size (currently 100). Each block has a checksum, which is used to determine whether it should be synchronized with the blocks on other nodes. If two blocks have the same ID and checksum on two nodes, then they are the same and no synchronization is required for that block. If the checksum is different, delta of the blocks is computed and and used for synchronization.

Attrribute stores contain attribute blocks. Frames contain row attribute stores and indexes contain column attribute stores. Because of that, block IDs and attributes for rows and columns should be retrieved separately.

The following algorithm may be used by the client side to retrieve row attributes export of an index from Pilosa:
```python
frames = index.frames()
for frame in frames:
    blockIDs = fetchRowBlockIDs(index, frame)
    for blockID in blockIDs:
        rowAttributes = fetchRowAttributes(index, frame, blockID)
        for rowID, attributes in rowAttributes.items():
            processRowAttributes(index, frame, rowID, attributes)
```

Export column attributes (from server to client):
```python
blockIDs = fetchColumnBlockIDs(index)
for blockId in blockIDs:
    columnAttributes = fetchColumnAttributes(index, blockID)
    for columnID, attributes in columnAttributes.items():
        processColumnAttributes(index, columnID, attributes)
```

### Blocks Response

Contains `id` and `checksum` fields for each block in JSON. Although only `id` is required for the actual export, `checksum` field may be useful for incremental exports (exporting only modified blocks).

Sample response:
```json
{
  "blocks": [
    {
      "checksum": "zUu3XfZUrvkD1J8Njc4yLIOxyHE=",
      "id": 1
    },
    {
      "checksum": "CRWqhIF2lWzfHx/ilMveBQ/8xc0=",
      "id": 10
    }
  ]
}
```

### Block Attributes Response

Contains the map of row or column IDs to attributes for a particular block in JSON. Also includes the index, block and frame (only for row attribute blocks). Including these extra fields may be useful for asynchronously receiving responses.

Sample row attributes response:
```json
{
  "attrs": {
    "100": {
      "foo": "bar"
    }
  },
  "block": 1,
  "index": "INDEX",
  "frame": "FRAME"
}
```

Sample column attributes response:
```json
{
  "attrs": {
    "100": {
      "foo": "bar"
    }
  },
  "block": 1,
  "index": "INDEX",
}
```

### HTTP Endpoints

* `fetchRowBlockIDs(INDEX, FRAME) -> GET /blocks/row-attrs?index=INDEX&frame=FRAME`: Returns blocks response for row attributes with the given `INDEX` and `FRAME`.

* `fetchColumnBlockIDs(INDEX) -> GET /blocks/column-attrs?index=INDEX`: Returns blocks response for column attributes with the given `INDEX`.

* `fetchRowAttributes(INDEX, FRAME, BLOCK_ID) -> GET /block/row-attrs?index=INDEX&frame=FRAME&block=BLOCK_ID`: Returns row attributes for the given block.

* `fetchColumnAttributes(INDEX, BLOCK_ID) -> GET /block/column-attrs?index=INDEX&block=BLOCK_ID`: Returns column attributes for the given block.

## Importing Attributes

We should use a different mechanism for importing attributes, since updating blocks explicitely is not supported. Attribute stores support bulk updates, which can be used for attribute imports.

`SetBulkAttrs` function of attribute stores expects a row/column ID to attributes mapping.

The following algorithm may be used by the client side to send row attributes import of an index to Pilosa:
```python
frames = index.frames()
for frame in frames:
    rowAttributes = frameRowAttributes(index, frame)
    for batch in makeBatch(rowAttributes):
        # batch = {"rowID": {"key": "value", ...}, ...}
        postRowAttributes(index, frame, batch)
```

Import column attributes (from client to server):
```python
columnAttributes = columnAttributes(index)
for batch in makeBatch(columnAttributes):
        # batch = {"rowID": {"key": "value", ...}, ...}
        postColumnAttributes(index, batch)
```

### Block Attributes Request

Contains the ID to attributes mapping in JSON.

Sample request:
```json
{
    "100": {
        "foo": "bar"
    },
    "200": {
        "age": 22
    }
}
```

### HTTP Endpoints

* `postRowAttributes(INDEX, FRAME, ATTRS) -> POST /block/row-attrs?index=INDEX&frame=FRAME [MARSHALED(ATTRS)]`: Receives row attributes from the client. The body of the request contains JSON marshaled attributes.

* `postColumnAttributes(INDEX, ATTRS) -> POST /block/column-attrs?index=INDEX [MARSHALED(ATTRS)]`: Receives column attributes from the client. The body of the request contains JSON marshaled attributes.

### Limiting Request/Response Data Size 

Response data size from export attribute operations are naturally constrained, since the response includes a single block which can contain attributes for at most *block size* row/columns (curently 100). But this introduces some overhead and may not be feasible for indexes with moderate size of rows/columns due to too many HTTP requests. It would be desirable to specify the blocks in the export request.

On the other hand, request data size is determined by the client. The client may send attributes for a very large number of rows/columns which would increase the time to send the data from the client to the server and place a high load on the server. We may impose a restriction on the size of the response body and return an error if the respons size is over a limit.

## Using Blocks for Bit Exports

Currently Pilosa exports all bits for a frame in CSV format (bit imports use protobuf). This is not scalable even for moderate sized data sets. We can use blocks to overcome this issue which would also help with making the bit exports use protobufs.

**Comment by raskle** [comment]
I'd like to take a step back and discuss why we would need to support exporting everything from Pilosa.  We say that Pilosa should not be used as your durable datastore, as there could be data inconsistencies.  Therefore it would be better for users to export this information for their traditional datastore that's used in conjunction with Pilosa instead of our application.

In regard to backing up data through export, I would recommend we look file system level tools rather than taxing the application and API.

If we do decide to support full data exports I would prefer that the public API did not require any knowledge of blocks.  That's just an extra layer of complexity we would be asking users to understand, and it provides little benefit.  I understand that this data, in fact all exports, could be very large.  Which is why I think we would need to look at some paginated approach or simply not supporting the feature.

I would prefer to focus this proposal on importing bulk attributes through the Import, and Input Definition API's.

**Comment by yuce** [comment]
@raskle I will touch the other points in your comments further, but I am curious about your point on pagination: how should we implement it?

**Comment by yuce** [comment]
@raskle 

File system level tools would be easy to use, we can just copy Pilosa data directory somewhere. But what do we do if we have to grow the cluster from 3 to 5 nodes? The data directories we got from nodes are only usable for 3 nodes. What do we do if we have to shrink the cluster from 5 to 3 nodes? Consider the taxi data backed up on a 3 node cluster by copying data files of those nodes. How do we use that data on a single node (e.g., to give it to users to experiment on it)? An even bigger problem is, how do we guarantee that the data files we backed up now works next year on a different Pilosa version?

If we allow users to save attributes next to their bits, I think we should support bulk importing and exporting their bits and attributes, for back ups, sharing data sets, taking their data to somewhere else or seeding another Pilosa server.

The great thing about blocks is they are very simple (as far I see). A block has an ID to distinguish it from other blocks; and it has a checksum, which changes if the block changes. The block has an upper limit on the number of items it contains, so they can naturally be used to implement paging. I think these are wonderful properties for an incremental backup system. It would work like:
1. get the blocks and save their ids and checksums somewhere
2. retrieve the bits and attributes and save them somewhere
3. in the future, get the blocks again and compare their ids and checksums to the saved ones
4. retrieve only the changed blocks.

Our users don't necessarily need to know about how blocks work; ideally the clients would cover the complexity (which is not very complex to begin with) but IMO think there's no harm in exposing this to users which would do more creative things with them.

My view on imports/exports vs input definition is at: https://github.com/pilosa/pilosa/issues/725#issuecomment-314492126

In Pilosa code, I didn't see a way of exporting attributes other than blocks. It would be great if you could point me in the right direction so we can compare approaches.

**Comment by addos** [comment]
Hi, I can't speak as much to what has been suggested in this proposal. But one thing I wish pilosa would make easier is the ability to automatically create non-existing indexes/frames when importing data using the pilosa import command.

**Comment by yuce** [comment]
@addos There's a proposal at: https://github.com/pilosa/pilosa/issues/725 which includes the feature you ask. Please upvote it if you like it or comment on it if you have other ideas.

In the mean time, you can use one of the client libraries to write a script which creates non-existing index/frames and import CSV data, it is pretty trivial. All the necessary steps are in READMEs of the corresponding clients. The steps are basically:
- Load the schema from the server
- Populate it with indexes and frames (index/frame names, options, ...)
- Sync the schema (non-existing indexes/frames will be created)
- Call import frame for each frame

Let me know if you have any questions.

Here's the list of READMEs. For Go and Java clients, the sections on imports/exports are documented in a PR:
- Go client README (the section on imports/exports will be merged to master soon): https://github.com/yuce/go-pilosa/blob/readme-update/README.md
- Java client README (the section on imports will be merged to master soon): https://github.com/yuce/java-pilosa/blob/readme-update/README.md
- Python client README: https://github.com/pilosa/python-pilosa/blob/master/README.md
