### ISSUE TITLE
provide backup/restore of full pilosa data

### ISSUE THREAD

**Issue by tgruben** [FeatureBaseDB/featurebase#888]
### Description
The current pilosa backup command requires an index,frame, and view names as input.  In order to perform a complete backup, every view must be manually requested.  This could be greatly simplified if the command handled all the details and produced a nice compressed file that could be restored at a later time.   

### Success criteria (What criteria will consider this ticket closeable?)
pilosa backup --uri HOST:IP   --outputDirectory /mnt/backup/
#this will produce a file /mnt/backup/backup20171011.pak
pilosa restore --uri HOST:ip backup20171011.pak

**Comment by jaffee** [comment]
perhaps not identical, but related: https://github.com/pilosa/pilosa/issues/725

**Comment by jaffee** [comment]
This import view work (unmerged) may end up being relevant to backup/restore strategy: https://github.com/pilosa/pilosa/pull/733

**Comment by jaffee** [comment]
this also may be relevant: https://github.com/pilosa/pilosa/pull/743
