### ISSUE TITLE
Handler plugins

### ISSUE THREAD

**Issue by codysoyland** [FeatureBaseDB/featurebase#997]
This ticket is a placeholder for future work in plugins.

PR #574 contained code that we chose not to merge yet. It may be useful for our future strategy with plugins. The relevant code is in this branch: https://github.com/pilosa/pilosa/tree/handler-plugins

**Comment by fsaintjacques** [comment]
Is this still relevant?

**Comment by travisturner** [comment]
@fsaintjacques we've had several attempts at introducing plugins at various places in the code. This was one attempt at designing a plugin before really understanding the use cases.

So to answer your question, I'd say this specific issue is not really relevant, but the concept of "plugins" is something we keep coming back to. If you have thoughts or example use cases that could inform how we might approach plugins in a useful way, that would be very helpful.
